{% set name = "openff-utilities" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-utilities/archive/v{{ version }}.tar.gz
  sha256: f17026ea8e0359ea7271953079392f6f5edea70dc582a2e59b3cc28a16e6fde2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8
    - importlib_resources
    - typing_extensions

test:
  imports:
    - openff.utilities

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of miscellaneous utility functions used by experimental OpenFF packages
  dev_url: https://github.com/openforcefield/openff-utilities

extra:
  recipe-maintainers:
    - mattwthompson
